//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoLojackABM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Cuentas = new HashSet<Cuenta>();
            this.Usuarios = new HashSet<Usuario>();
        }
    
        public int idCliente { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string localidad { get; set; }
        public string partido { get; set; }
        public string provincia { get; set; }
        public string cuit { get; set; }
        public string email { get; set; }
        public string fax { get; set; }
        public bool inhabilitado { get; set; }
        public System.DateTime fechaAlta { get; set; }
        public int usuarioAlta { get; set; }
        public System.DateTime fechaModificacion { get; set; }
        public int usuarioModificacion { get; set; }
        public Nullable<System.DateTime> fechaBaja { get; set; }
        public Nullable<int> usuarioBaja { get; set; }
        public int idPais { get; set; }
        public Nullable<int> idCuenta { get; set; }
        public bool vistaInternoDesvios { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
        public virtual ICollection<Cuenta> Cuentas { get; set; }
        public virtual ICollection<Usuario> Usuarios { get; set; }
    }
}
