//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoLojackABM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        public Cuenta()
        {
            this.Entidads = new HashSet<Entidad>();
            this.Equipoes = new HashSet<Equipo>();
            this.ProcedimientoEmergencias = new HashSet<ProcedimientoEmergencia>();
            this.Usuarios = new HashSet<Usuario>();
        }
    
        public int idCuenta { get; set; }
        public string nombre { get; set; }
        public int idClienteControlador { get; set; }
        public Nullable<bool> mapGuideEnabled { get; set; }
        public Nullable<bool> googleMapsEnabled { get; set; }
        public int mapsEnabled { get; set; }
    
        public virtual ICollection<Entidad> Entidads { get; set; }
        public virtual ICollection<Equipo> Equipoes { get; set; }
        public virtual ICollection<ProcedimientoEmergencia> ProcedimientoEmergencias { get; set; }
        public virtual ICollection<Usuario> Usuarios { get; set; }
    }
}
