//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoLojackABM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entidad
    {
        public int idEntidad { get; set; }
        public string nombre { get; set; }
        public int estado { get; set; }
        public int idNivelServicio { get; set; }
        public string plantillaSuceso { get; set; }
        public int cadenciaReporte { get; set; }
        public System.DateTime fechaAlta { get; set; }
        public int usuarioAlta { get; set; }
        public System.DateTime fechaModificacion { get; set; }
        public int usuarioModificacion { get; set; }
        public Nullable<System.DateTime> fechaBaja { get; set; }
        public Nullable<int> usuarioBaja { get; set; }
        public string comentario { get; set; }
        public string telefono { get; set; }
        public Nullable<int> idProcedimiento { get; set; }
        public Nullable<int> idCuenta { get; set; }
    
        public virtual NivelServicio NivelServicio { get; set; }
    }
}
