//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoLojackABM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class EquipoTipo
    {
        public EquipoTipo()
        {
            this.Equipoes = new HashSet<Equipo>();
        }
    
        public int idEquipoTipo { get; set; }
        [Required(ErrorMessage = "El campo Descripción es obligatorio.")]
        [StringLength(50, ErrorMessage = "El campo Descripción no puede exceder los 50 caracteres.")]
        public string descripcion { get; set; }
        [Required(ErrorMessage = "El campo Cantidad de Sensores es obligatorio.")]
        [Range(0, int.MaxValue,ErrorMessage = "Cantidad de Sensores no puede ser negativo.")]
        public int cantSensores { get; set; }
        public System.DateTime fechaAlta { get; set; }
        public int usuarioAlta { get; set; }
        public Nullable<System.DateTime> fechaBaja { get; set; }
        public Nullable<int> usuarioBaja { get; set; }
    
        public virtual ICollection<Equipo> Equipoes { get; set; }
    }
}
