//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoLojackABM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Lojack_PruebaEntities : DbContext
    {
        public Lojack_PruebaEntities()
            : base("name=Lojack_PruebaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cuenta> Cuentas { get; set; }
        public DbSet<Entidad> Entidads { get; set; }
        public DbSet<Equipo> Equipoes { get; set; }
        public DbSet<EquipoTipo> EquipoTipoes { get; set; }
        public DbSet<NivelServicio> NivelServicios { get; set; }
        public DbSet<ProcedimientoEmergencia> ProcedimientoEmergencias { get; set; }
        public DbSet<Usuario> Usuarios { get; set; }
    }
}
